spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/store?characterEncoding=UTF-8
    username: root
    password: Hzy321
server:
  port: 8085
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.huziyun.store.entity
  configuration:
    map-underscore-to-camel-case: true